### ISSUE TITLE
PizzaCalculator: US-1

### ISSUE THREAD

**Issue by jonbertelsen** [jonbertelsen/lifehack_spring_2024#3]
**Tasks**

- [x] Create Figma Mockup
- [x] Project setup with Controller etc
- [x] Implement simple input form
- [x] Implement simple controller to receive form data
- [x] Implement simple recipe page
- [x] Code backend

**User story**

US-1: Som pizzabager vil jeg kunne indtaste antal pizzaer, deres vægt, hydreringsprocent og lufttemperatur og få en samlet udskrift med angivelse af ingredienser og fremgangsmåde, så jeg kan bage verdens bedste napolitanske pizzaer - margaritha style.

**Accept-kriterium:**

Givet at jeg ønsker 3 pizzaer, der hver skal have en bund á 285g dej, en hydreringsprocent på 70 og lufttemperaturen er 22 grader, og at jeg er på Pizzacalulator websiden
Når jeg har indtastet info i en formular
Så forventer jeg en komplet opskrift med angivelse af ingredienser, mængder og en beskrivelse af fremgangsmåde og tidsforbrug.
